name: 🐛 버그 리포트
description: 버그를 발견하셨나요? 자세한 내용을 알려주세요!
title: "[Bug] "
labels: ["bug", "needs-triage"]
assignees:
  - DainoJung

body:
  - type: markdown
    attributes:
      value: |
        버그 리포트를 작성해주셔서 감사합니다! 가능한 한 자세히 작성해주시면 빠른 해결에 도움이 됩니다.

  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 버그 설명
      description: 발생한 버그에 대해 명확하고 간결하게 설명해주세요.
      placeholder: 버그가 무엇인지 설명해주세요...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🔄 재현 방법
      description: 버그를 재현하는 단계를 설명해주세요.
      placeholder: |
        1. '...' 으로 이동
        2. '...' 클릭
        3. '...' 까지 스크롤
        4. 오류 발생
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ 예상된 동작
      description: 어떤 일이 일어나야 한다고 예상했나요?
      placeholder: 예상했던 동작을 설명해주세요...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ 실제 동작
      description: 실제로 어떤 일이 일어났나요?
      placeholder: 실제로 발생한 동작을 설명해주세요...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🖥️ 환경 정보
      description: 사용 중인 환경에 대한 정보를 제공해주세요.
      value: |
        - OS: [예: macOS 14.3.0, Windows 11, Ubuntu 22.04]
        - Python 버전: [예: 3.9.0]
        - 브라우저: [예: Chrome 120.0]
        - 기타:
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 📎 추가 정보
      description: 스크린샷, 로그, 또는 문제에 대한 추가 컨텍스트를 제공해주세요.
      placeholder: 추가 정보나 스크린샷을 첨부해주세요...

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ 체크리스트
      description: 버그 리포트를 제출하기 전에 다음 사항들을 확인해주세요.
      options:
        - label: 기존 이슈를 검색했고, 동일한 문제가 보고되지 않았습니다.
          required: true
        - label: 최신 버전을 사용하고 있습니다.
          required: true
        - label: 문제 재현을 위한 충분한 정보를 제공했습니다.
          required: true 